export var stationList={breakbeatbig:["fngl - extra.mp3",
"luce - combobreaker.mp3",
"luce - control.mp3",
"luce - fading out.ogg",
"luce - grave diggah.ogg",
"luce - lazybreakjams - 120.wav",
"luce - matriksextnd.ogg",
"luce - packed.mp3",
"luce - partyline.wav",
"luce - pow.wav",
"Luce - Primetime [BAM-004].mp3",
"luce - sapphire.mp3",
"luce - shank.wav",
"luce - traitor.mp3"],
bumps:["blurry.mp3",
"bump1.mp3",
"bump2.mp3",
"bump3.mp3",
"bump4.mp3",
"bump5.mp3",
"bump6.mp3",
"iloveyoubump.mp3",
"sysbump.mp3",
"sysbump2.mp3"],
dubstepgrime:["fngl - modwub.wav",
"luce - bloke.mp3",
"luce - wash.ogg",
"ohmrec - otherworld.mp3",
"trashed - Boxer.wav",
"trashed - green.mp3",
"trashed - proof.mp3",
"trashed - Untitled.0.mp3"],
footworktech:["luce - connected.wav",
"luce - eloquent.mp3",
"luce - infectious.ogg"],
hiphop:["burg - expressions [001].mp3",
"burg - final fight.mp3",
"burg - keep dreaming.mp3",
"burg - kirby.mp3",
"burg - smth&wsn.mp3",
"burg - space dame.ogg",
"burg - space.ogg",
"burg - tick tock.mp3",
"fngl - mpk.wav",
"luce - bap [ft. Ronnie Chea].mp3",
"luce - boom.ogg",
"luce - dreams.mp3",
"luce - funky.mp3",
"luce - summit.mp3",
"luce - takes2 (vibe mix).ogg",
"luce - window cleaner.mp3",
"luce - wobbly.mp3",
"luce_-_4567.ogg",
"luce_-_dreams.ogg",
"luce_-_pow_lastnight_medium_mix.ogg"],
housetechno:["luce - dance with it.ogg",
"luce - new year.mp3",
"luce - not yet (thrunthru mix).ogg",
"luce - past (ft renz).mp3",
"luce - smoked out.mp3"],
jsr:["01. Let Mom Sleep.mp3",
"02. Humming The Bassline.mp3",
"03. That's Enough.mp3",
"04. Everybody Jump Around.mp3",
"05. Sneakman.mp3",
"06. Sweet Soul Brother.mp3",
"07. Rock It On.mp3",
"08. Electric Tooth Brush.mp3",
"09. Moody's Shuffle.mp3",
"10. Grace And Glory.mp3"],
jsrf:["01 THE CONCEPT OF LOVE.mp3",
"02 FLY LIKE A BUTTERFLY.mp3",
"03 FUNKY DEALER.mp3",
"04 SHAPE DA FUTURE.mp3",
"05 TEKNOPATHETIC.mp3",
"06 OLDIES BUT HAPPIES.mp3",
"07 LIKE IT LIKE THIS LIKE THAT.mp3",
"08 I LOVE LOVE YOU  JSRF version.mp3",
"09 BABY-T  JSRF version.mp3",
"10 HUMMING THE BASSLINE (D.S. Remix).mp3",
"11 ROCK IT ON (D.S. Remix).mp3",
"12 SNEAKMAN (Toronto Mix).mp3",
"13 WHAT ABOUT THE FUTURE.mp3",
"14 BOKFRESH.mp3",
"15 LET MOM SLEEP (No Sleep Remix).mp3",
"16 THAT'S ENOUGH (B.B.Rights Mix).mp3",
"17 SWEET SOUL BROTHER (B.B.Rights Mix).mp3",
"18 GRACE & GLORY (B.B.M.H.Mix).mp3",
"19 JET SET MEDLEY FUTURE.mp3",
"20 JET SET STATION 2.mp3",
"21 JET SET GROOVE 3.mp3",
"22 JET SET GROOVE 4.mp3"],
junglednb:["ankaph - away (luce jungle remix).wav",
"Kepz - Q7 (luce mix).ogg",
"luce - ascension.mp3",
"luce - awakening.wav",
"luce - do you.mp3",
"luce - encore.mp3",
"luce - energy.ogg",
"luce - genesis.mp3",
"luce - inline.wav",
"luce - itsnotover.mp3",
"luce - itsnotoveryet-full.mp3",
"luce - lost soul (2022 mix).ogg",
"luce - network.wav"],
live:["10_PM_in_Tokyo.mp3",
"ETT1800.mp3",
"thesesongshavethesamekeyandbpm.mp3",
"Untitled_song_4.mp3",
"Vadell Gabriel - Professor Qrazee.mp3",
"what.mp3"],
memes:["audio (1).wav",
"audio.wav",
"audio_1.wav",
"audio_18.wav",
"doinurmombut.mp3",
"holyshit.wav",
"rpg_soundtracks_be_like.mp3"],
rand:[]};