export var stationList={jsr:["01. Let Mom Sleep.mp3",
"02. Humming The Bassline.mp3",
"03. That's Enough.mp3",
"04. Everybody Jump Around.mp3",
"05. Sneakman.mp3",
"06. Sweet Soul Brother.mp3",
"07. Rock It On.mp3",
"08. Electric Tooth Brush.mp3",
"09. Moody's Shuffle.mp3",
"10. Grace And Glory.mp3"],
jsrf:["01 THE CONCEPT OF LOVE.mp3",
"02 FLY LIKE A BUTTERFLY.mp3",
"03 FUNKY DEALER.mp3",
"04 SHAPE DA FUTURE.mp3",
"05 TEKNOPATHETIC.mp3",
"06 OLDIES BUT HAPPIES.mp3",
"07 LIKE IT LIKE THIS LIKE THAT.mp3",
"08 I LOVE LOVE YOU  JSRF version.mp3",
"09 BABY-T  JSRF version.mp3",
"10 HUMMING THE BASSLINE (D.S. Remix).mp3",
"11 ROCK IT ON (D.S. Remix).mp3",
"12 SNEAKMAN (Toronto Mix).mp3",
"13 WHAT ABOUT THE FUTURE.mp3",
"14 BOKFRESH.mp3",
"15 LET MOM SLEEP (No Sleep Remix).mp3",
"16 THAT'S ENOUGH (B.B.Rights Mix).mp3",
"17 SWEET SOUL BROTHER (B.B.Rights Mix).mp3",
"18 GRACE & GLORY (B.B.M.H.Mix).mp3",
"19 JET SET MEDLEY FUTURE.mp3",
"20 JET SET STATION 2.mp3",
"21 JET SET GROOVE 3.mp3",
"22 JET SET GROOVE 4.mp3"],
live:["iloveyoubump.mp3",
"what.mp3"],
memes:["doinurmombut.mp3"],
rand:[]};